spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.110.13:3306/oauth2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: O1qa9OjN